### ISSUE TITLE
希望定时开关也支持单控模式

### ISSUE THREAD

**Issue by lphgor** [ZXQ-Kyle/N1Script#1]
现在的定时功能只能同时设置4个开关的状态，使用起来不是很方便。
希望可以只设置某一个或其中几个的开关定时任务，执行任务时其余开关状态保持不变。

**Comment by ZXQ-Kyle** [comment]
下个版本就加

**Comment by ZXQ-Kyle** [comment]
> 现在的定时功能只能同时设置4个开关的状态，使用起来不是很方便。
> 希望可以只设置某一个或其中几个的开关定时任务，执行任务时其余开关状态保持不变。

下个版本就加
