### ISSUE TITLE
使用frp映射8800端口不起作用

### ISSUE THREAD

**Issue by sunhf-git** [ZXQ-Kyle/N1Script#3]
我分别使用frp映射了 8800端口(tcp) 和 8880端口（http）。http接口访问正常，可以获得插座的信息。 但8800端口（映射端口为9980），却无法控制插座的开关。frpd的配置信息如下。
![image](https://user-images.githubusercontent.com/61272249/92307875-11d8a900-efcc-11ea-9584-eed01fe5fa82.png)
![image](https://user-images.githubusercontent.com/61272249/92307892-2a48c380-efcc-11ea-821b-e54e3d4f2a4f.png)
![image](https://user-images.githubusercontent.com/61272249/92307903-3fbded80-efcc-11ea-8a3f-eed3d0fcb8a9.png)

app中填写了对应的端口号和域名，出现上述情况，是我哪里操作不当吗？

**Comment by ZXQ-Kyle** [comment]
局域网直接控制可以吗？
frp配置贴一下我的
[dc1s]
remote_port=xxx
local_ip=127.0.0.1
local_port=8800
privilege_mode=true
type = tcp
use_encryption = true
use_compression = true

**Comment by sunhf-git** [comment]
> 局域网直接控制可以吗？
> frp配置贴一下我的
> [dc1s]
> remote_port=xxx
> local_ip=127.0.0.1
> local_port=8800
> privilege_mode=true
> type = tcp
> use_encryption = true
> use_compression = true

局域网直接控制是可以的，我尝试了下上述的配置。似乎仍然无法控制开关。
![16692EDA17335AD295C2711F67A830A5](https://user-images.githubusercontent.com/61272249/92308214-d7bcd680-efce-11ea-951c-d158f28630e2.jpg)
![image](https://user-images.githubusercontent.com/61272249/92308227-ed320080-efce-11ea-9f73-8ef97b8a5d75.png)

**Comment by ZXQ-Kyle** [comment]
dc的域名指向了服务器地址吗？
如果指向了的话，那按照最基本配置，http不要使用subdomain，使用frp服务器域名+远程端口，这样应该没问题的

**Comment by sunhf-git** [comment]
> dc的域名指向了服务器地址吗？
> 如果指向了的话，那按照最基本配置，http不要使用subdomain，使用frp服务器域名+远程端口，这样应该没问题的

问题解决了，我放弃了http映射，全部改用了tcp映射，且绑定的端口号与dc服务保持一致。就可以正常使用了
![image](https://user-images.githubusercontent.com/61272249/92314817-aca6a700-f00f-11ea-96b9-15d15f785e66.png)
